### ISSUE TITLE
모든 게시물 정보를 불러올 때 좋아요 개수 JOIN 처리

### ISSUE THREAD

**Issue by choewy** [PBL-magazine/backend-choewy#2]
현재 구현하고자 하는 것을 쿼리문으로 나타내면 다음과 같습니다.

```sql
SELECT *, 
(
	SELECT COUNT(*) FROM likes
	WHERE post_id = posts.post_id
) as likes
FROM posts
INNER JOIN 
(
	SELECT user_id, email, nickname 
	FROM users
) as users
ON users.user_id = posts.user_id;
```

![스크린샷, 2022-04-16 20-40-00](https://user-images.githubusercontent.com/70950533/163673519-9db14f4b-78a3-4db8-ad31-62f8450f9c2b.png)

Sequelize에서 이러한 방식으로 구현하기 위한 방법을 찾아야 합니다.

**Comment by diasm3** [comment]
확인했습니다. 
구현 완료하면 코드 공유 하겠습니다~

**Comment by choewy** [comment]
- [`server/src/post/post.service.js`](https://github.com/PBL-magazine/backend-choewy/blob/87a8dcc07e158d27ca6c9289d77a3fd905e8091f/server/src/post/post.service.js)

```js
/* Inner Function getPosts  */
const postsAll = await Post.findAll({
  include: [
    {
      model: User,
      as: 'user',
      attributes: ['email', 'nickname'],
    },
  ],
});

const postValues = postsAll.map((el) => el.get({ plain: true }));

const likesAll = await Like.findAll();
const likesValues = likesAll.map((el) => el.get({ plain: true }));

return postValues.map((post) => {
  const likes = likesValues.filter((like) => like.post_id === post.post_id );
  return { ...post, likes: likes.length };
});
```

일단은 이용우 매니저님께서 답변 해주신 내용을 토대로 구현한 방법을 공유 드립니다!

- "Sequelize 내부의 JOIN을 이용하기 보다는 두 개의 쿼리 또는 서브 쿼리를 사용하는 편이 더 낫겠다"

위의 방법은 두 개의 퀴리를 사용해서 데이터를 전부 불러온 후 `map`과 `filter`를 통해 좋아요 수를 추가하는 방법입니다.

1. 첫 번째 쿼리(`postsAll`) : 모든 게시물 정보 조회 + 사용자 정보(이메일, 닉네임) JOIN
2. 두 번째 쿼리(`likesAll`) : 모든 게시물의 좋아요 정보 조회

`map`을 통해 데이터를 가공하기 위해서는 쿼리로부터 꺼내온 객체 정보 중 `dataValues`를 사용해야 하는데, 이를 위해 다음과 같은 처리를 해주었습니다.

```js
const postValues = postsAll.map((el) => el.get({ plain: true }));
const likesValues = likesAll.map((el) => el.get({ plain: true }));
```

- 참고자료 : https://juhi.tistory.com/13

**Comment by moto4321** [comment]
확인했습니다! 멋있으십니다...👍
